### ISSUE TITLE
Aligning word cloud, selfie, and interactions graph

### ISSUE THREAD

**Issue by jacquelinelviola** [bzamansky/cs4300sp2016-PowerPlay#1]
We need to vertically align the word cloud with the selfie image. They are now in the same div (which is good). Graph should also not overlap the image. See screenshot below:

<img width="1440" alt="screen shot 2016-04-24 at 9 56 23 pm" src="https://cloud.githubusercontent.com/assets/7388036/14772060/6c3f33a4-0a67-11e6-99ba-b315a932a564.png">

**Comment by remoz** [comment]
Fixed.
