### ISSUE TITLE
Search for candidates on different parts of name

### ISSUE THREAD

**Issue by bzamansky** [bzamansky/cs4300sp2016-PowerPlay#6]
"I think your user interface is intuitive, though perhaps you should specify somewhere that you only allow users to search for the LAST NAME of each candidate ("Bernie Sanders" fails while "Sanders" succeeds). You could always circumvent this issue by giving search suggestions if there is no exact match (this does not have to be done for Tuesday)."

**Comment by remoz** [comment]
Mostly finished, just need to address why it returns O'Malley when it's an empty entry in Candidates.

**Comment by remoz** [comment]
Issues fixed. (Thanks Batya).
